[package]
name = "hashiverse-integration-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "test-harness"
path = "src/bin/test_harness.rs"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
scopeguard = { workspace = true }
parking_lot = { workspace = true }
hashiverse-lib = { path = "../hashiverse-lib" }
hashiverse-server-lib = { path = "../hashiverse-server-lib" }
tokio-util = { version = "0.7.14", features = ["codec", "rt"] }
tokio = { version = "1.45", features = ["macros", "time", "rt", "io-util", "rt-multi-thread"] }
futures = "0.3.31"
rustls = { version = "0.23", default-features = false, features = ["ring", "tls12"] }
clap = { version = "4.5.38", features = ["derive"] }
