name: publish-hashiverse-lib

on:
  release:
    types: [released, prereleased]
  workflow_dispatch:
    inputs:
      target:
        description: "Where to publish"
        type: choice
        required: true
        default: "dry-run"
        options:
          - dry-run
          - crates-io

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-dry-run:
    name: cargo publish --dry-run
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.target == 'dry-run' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: ./.github/actions/set-cargo-version-from-tag

      - uses: ./.github/actions/install-rust-toolchain

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "hashiverse-rust-publish"
          workspaces: hashiverse-rust -> target

      - name: cargo publish --dry-run
        working-directory: hashiverse-rust
        run: cargo publish --dry-run -p hashiverse-lib

  publish-crates-io:
    name: publish to crates.io
    if: |
      (github.event_name == 'release') ||
      (github.event_name == 'workflow_dispatch' && inputs.target == 'crates-io')
    runs-on: ubuntu-latest
    environment:
      name: crates-io
      url: https://crates.io/crates/hashiverse-lib
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: ./.github/actions/set-cargo-version-from-tag

      - uses: ./.github/actions/install-rust-toolchain

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "hashiverse-rust-publish"
          workspaces: hashiverse-rust -> target

      - name: cargo publish
        working-directory: hashiverse-rust
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish -p hashiverse-lib
